### ISSUE TITLE
test_program.ps syntax error at the last line

### ISSUE THREAD

**Issue by mlouielu** [chenwei-tw/Pascal-Like-Interpreter#1]
```
    _a := _a div 2
```

should be 

```
    _a := _a div 2;
```

otherwise it should trigger syntax error.

**Comment by furuame** [comment]
In Pascal, end of the last statement in a block doesn't need ```;```

Referenced from [Pascal (Programming Language)](https://en.wikipedia.org/wiki/Pascal_(programming_language))

It's okay to modify grammar if we want to design a new programming language, while the name of this repo should be modified XD

**Comment by mlouielu** [comment]
Ah, I see. Longtime doesn't write Pascal... forgot this feature.
